### ISSUE TITLE
Seems like there is a large stutter on level.End(true) when the system checks to see if the missions for that level have been completed.

### ISSUE THREAD

**Issue by prodigga** [soomla/unity3d-levelup#10]
Testing on my Nexus 5, there is a very noticeable performance hick up when I end a level. My level has a mission inside it, which is unlocked when the score for that level reaches 3 (3 stars). The mission rewards the user with a currency pack, and it is scheduled to only run once.

I have the Grow Highway, Levelup and Store modules initialized.

**Comment by refaelos** [comment]
@prodigga you're right. We saw this and we're working on a fix.

Also, I would suggest you to post questions on http://answers.soom.la. You might get better help there.

**Comment by prodigga** [comment]
No problem, figured this was more of a problem with the system than a problem I needed help with so I thought I'd report it. :)

**Comment by refaelos** [comment]
Thanks. I'll close this for now.

**Comment by prodigga** [comment]
Cool. Is there a duplicate issue that I could follow or something so I know when this gets fixed?

**Comment by refaelos** [comment]
Post an issue on the forum and we'll post there when it's done.

On that issue mention `@shubin_fedor` when you're there.

**Comment by prodigga** [comment]
Isnt that what this issue tracker is for? Or should I avoid reporting bugs here in the future and just use the forum?

**Comment by refaelos** [comment]
It's just where all people are seeing issues regarding SOOMLA.
