### ISSUE TITLE
Error while importing asset

### ISSUE THREAD

**Issue by Droidspirit** [soomla/unity3d-levelup#2]
Hello,

i got the following error while importing the all-in-one asset:

Could not create a directory for asset

If i trying it step by step the same error occurs on unity3d-profile asset.

Whats wrong?

Best regards

**Comment by staakman** [comment]
Sounds like quite a unique error. 

Although I haven't tried with the latest version, in the past I didn't get this error when i import the Unity3D package. Do you've the apropiate rights to create folders on your computer?

Does this happen only with the Unity-3D-Profile package? What happens if you import other packages?

**Comment by Droidspirit** [comment]
I have tested it again. The system is a windows 7 professional with admin rights and unity in version 4.6.2f1

If i create a new 2d project in users home directory the import of the assets (the single assets such as the all in one assets) works fine.

But if i create a new 2d project under a custom location (here: C:\MyFiles\Droidspirit\Android Development\MyAndroidDev\unity_workspace\NewSoomlaTestProject) the import of the asset soomla-unity3d-profile failed with the following message: 

Error while importing package: Could not create directory for asset

The import of the other assets works fine. I have enough disc space and write permissions on the folder.

Its curious.

**Comment by refaelos** [comment]
@Droidspirit can you try:
1. Import the package (get the error)
2. wait a few seconds for everything to settle down.
3. Delete log
4. Import same package again

Let me know if you get the error the second time.

**Comment by Droidspirit** [comment]
@refaelos 
I get the error a second time.

1. Import asset 1 + 2
2. Import asset 3
3. Error while importing package: Could not create directory for asset
4. Drinking coffee
5. Import asset 3 again
6. Same error

**Comment by Droidspirit** [comment]
Okay, when i copy the files to the assetfolder of my unity-projekt manually with file explorer, i get the error while copying the folder WebPlayerTemplates:

GPPNativeShareBuilderImpl.storyboardc
Filename is to large for target folder

My Unity-Project-Path is: C:\MyFiles\Droidspirit\Android Development\MyAndroidDev\unity_workspace\TestProject\Assets

When i copy my unity project to another location (c:\Myfiles\Testproject), then it works fine.

**Comment by refaelos** [comment]
@sluzky can you take a look?

**Comment by staakman** [comment]
"Filename is to large for target folder". Maximum file name length on a Windows machine is 260 characters. Doesn't sound to me like a soomla related bug. Especially when it works on a different location on your harddrive.

http://windows.microsoft.com/en-us/windows/file-names-extensions-faq#1TC=windows-7

**Comment by sluzky** [comment]
@refaelos we can't do anything about windows filename restrictions... people will just have to use less folders I guess.

**Comment by refaelos** [comment]
@sluzky I guess you're right. @Droidspirit does it answers your question?

**Comment by Droidspirit** [comment]
Thank you for the great support. Question is answered. I copy the project to another location :-)
