### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by forrestguice** [soomla/unity3d-levelup#23]
The docs previously at http://know.soom.la/unity/levelup/levelup_model missing. This isn't too surprising given the announcement at http://blog.soom.la/category/announcement informing that support for LevelUp has been dropped.

Where is the documentation that was previously available? It was useful.

**Comment by dafimor** [comment]
Hi @forrestguice,
You can find all the documentation under the [Wiki section](https://github.com/soomla/unity3d-levelup/wiki) here in github.

![LevelUp Wiki](https://www.dropbox.com/s/xvhpo64rn8f1yts/levelup_wiki.png?raw=1)

**Comment by forrestguice** [comment]
Awesome. Thanks a bunch. :)
